@ECHO OFF

TITLE MAIN BATCH FILE

SET MAIN_PATH=%~dp0
SET PRE_PATH=%MAIN_PATH%PREREQUISITES


REM ADDING NIA USER
SET NEW_USER=%PRE_PATH%\NEW_USER.bat
echo %NEW_USER%


REM CONFIGURING MOBILE 2 ADAPTER TO DHCP
SET MOBILE_2_CONFIG=%PRE_PATH%\MOBILE_NET_CONFIG.bat
%MOBILE_2_CONFIG%

REM RENAMING USB DRIVE
SET USB_RENAME=%PRE_PATH%\RENAME_USB_DRIVE.bat
%USB_RENAME%


REM INSTALLING PREREQUISITES

REM INSTALLING CODEMETER
SET CODEMETER_PATH=%MAIN_PATH%1_CodeMeter\INSTALL.bat
ECHO %CODEMETER_PATH%

REM ZEBRA
SET ZEBRA_PATH=%MAIN_PATH%2_Dermalog_SW_Preq\1_Enrollment\01_Barcode-Scanner\INSTALL.bat
ECHO %ZEBRA_PATH%

PAUSE