@ECHO OFF
REM change the mobile net config

SET ADAPTER=Mobile 2

ECHO Updating %ADAPTER% MOBILE net Config...

NETSH INTERFACE IPV4 SHOW CONFIG NAME="%ADAPTER%"
NETSH INTERFACE IP SET ADDRESS "%ADAPTER%" dhcp

PAUSE