@ECHO OFF

TITLE CREATE TERMINMAL CERTIFICATE

SET C_PKI_TOOLS_DESTINATION=C:\PKI_Tools

CD %C_PKI_TOOLS_DESTINATION%\CVCTool

SET G_K_R_CA_EID=generateKeysAndRequestsICA_EIDBATCH

REM EXECUTING THE GENERATE REQUEST BATCH
ECHO EXECUTING THE GENERATE REQUEST BATCH
%G_K_R_CA_EID%

SET PREFIX_EID=GHEID00
SET PREFIX_ICAO=GHICAO0

SET MRW_NUMBER=%username:~3,4%

SET EID_GH=GHICAO0%MRW_NUMBER%00001
SET ICAO_GH=GHICAO0%MRW_NUMBER%00001

REM CREATING USER FOLDER ON THE USB DRIVE IF IT DOES NOT EXIST
SET USB_USER_FOLDER_PATH=%USB_DRIVE_LETTER%:\%username%
IF %USB_USER_FOLDER_PATH% NOT EXIST (
	MKDIR %USB_USER_FOLDER_PATH%
)

REM COPYING .cvcr CERFITIFICATE FILES ON TO THE USB DRIVE
COPY %EID_GH%.cvcr %USB_USER_FOLDER_PATH%
COPY %ICAO_GH%.cvcr %USB_USER_FOLDER_PATH%

PAUSE