@ECHO OFF

TITLE CREATE CLIENT CERTIFICATE

SET C_PKI_TOOLS_DESTINATION=C:\PKI_Tools

CD %C_PKI_TOOLS_DESTINATION%\CreateDVclientcert

SET CREATE_REQUEST_BATCH=createrequestBatch.bat

%CREATE_REQUEST_BATCH%

REM COPYING .csr CERFITIFICATE FILES ON TO THE USB DRIVE

REM CREATING USER FOLDER ON THE USB DRIVE IF IT DOES NOT EXIST
SET USB_USER_FOLDER_PATH=%USB_DRIVE_LETTER%:\%username%
IF %USB_USER_FOLDER_PATH% NOT EXIST (
	MKDIR %USB_USER_FOLDER_PATH%
)

set PREFIX_EID=GHEID00
SET PREFIX_ICAO=GHICAO0

SET MRW_NUMBER=%username:~3,4%

set EID_GH=%PREFIX_EID%%MRW_NUMBER%
set ICAO_GH=%PREFIX_ICAO%%MRW_NUMBER%

COPY %EID_GH%.csr %USB_USER_FOLDER_PATH%
COPY %ICAO_GH%.csr %USB_USER_FOLDER_PATH%

PAUSE