SET PKI_TOOLS_PATH = Windows(C:)/'PKI tools'

REM GETTING THE USB DRIVE LETTER FROM THE USER
SET /p USB_DRIVE = "ENTER USB DRIVE LETTER: "

REM CHECKING IF FOLD EXISTS
IF PKI_TOOLS_PATH NOT EXIST (
	SET FOLDER = %USB_DRIVE%/'4_PKI TOOLS'
	
	REM STEP ONE
	XCOPY %FOLDER% %PKI_TOOLS_PATH% /E
)

SET DEMALOG_C_PATH = 'Windows(C:)/Program files (x86)/DERMALOG'

REM COPYING EID CSCA FILE
SET EID_CSCA_PATH = ""
SET EID_CSCA_DESTINATION_PATH = 'CardReaderService/Certificates/eid/csca'

COPY %EID_CSCA_PATH% %DEMALOG_C_PATH%/%EID_CSCA_DESTINATION_PATH%

REM COPYING ICAO CSCA FILE
SET ICAO_CSCA_PATH = ""
SET ICAO_CSCA_DESTINATION_PATH = 'CardReaderService/Certificates/icao/csca'

COPY %ICAO_CSCA_PATH% %DEMALOG_C_PATH%/%ICAO_CSCA_DESTINATION_PATH%

REM COPYING THE TRUSTSTROE CERTIFICATE
SET TRUSTSTROE_PATH = ""
SET TRUSTSTROE_DESTINATION_PATH = CardReaderService/keyStore

COPY %TRUSTSTROE_PATH% %DEMALOG_C_PATH%/%TRUSTSTROE_DESTINATION_PATH%

REM COPYING BARCODE CERTIFICATE
SET BARCODE_PATH = ""
SET BARCODE_DESTINATION_PATH = CardReaderService/keyStore

COPY %BARCODE_PATH% %DEMALOG_C_PATH%/%BARCODE_DESTINATION_PATH%

REM COPYING EID AND ICAO cvcert
SET EID_CV_CERT_PATH = ""
SET EID_DV_AND_CVCA_LINK_DESTINATION_PATH = CardReaderService/Certificates/eid/dv_and_cvca_link 

COPY %EID_CV_CERT_PATH% %DEMALOG_C_PATH%/%EID_DV_AND_CVCA_LINK_DESTINATION_PATH%

SET ICAO_CV_CERT_PATH = ""
SET ICAO_DV_AND_CVCA_LINK_DESTINATION_PATH = CardReaderService/Certificates/icao/dv_and_cvca_link 

COPY %ICAO_CV_CERT_PATH% %DEMALOG_C_PATH%/%ICAO_DV_AND_CVCA_LINK_DESTINATION_PATH%


