@ECHO OFF

TITLE PKI INSTALLATION

REM Copying pki tools folder to c drive
ECHO COPYING PKI_TOOLS FOLDER TO C DRIVE
SET PKI_TOOLS_NAME=4_PKI_Tools
SET USB_PKI_TOOLS_PATH=%~dp0%PKI_TOOLS_NAME%
SET C_PKI_TOOLS_DESTINATION=C:\PKI_Tools
XCOPY %USB_PKI_TOOLS_PATH% %C_PKI_TOOLS_DESTINATION% /E/Y/I


REM Cd into C Drive before runing following batch files

REM Create Terminal Certificate
ECHO Create Terminal Certificate
SET CREATE_TERMINAL_CERTIFICATE=CREATE_TERMINAL_CERTIFICATE.bat
CALL %CREATE_TERMINAL_CERTIFICATE%


REM Create Client Certificate
ECHO Create Client Certificate
SET CREATE_CLIENT_CERTIFICATE=CREATE_CLIENT_CERTIFICATE.bat
CALL %CREATE_CLIENT_CERTIFICATE%


REM Create Keystore Certificate
ECHO Create Keystore Certificate
SET CREATE_KEYSTORE_CERTIFICATE=CREATE_KEYSTORE_CERTIFICATE.bat
%CREATE_KEYSTORE_CERTIFICATE%

PAUSE